### ISSUE TITLE
Disappearing Framework 

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#468] opened 2019-01-24 21:54 UTC
Reported by Michael Parsons: 
I was checking on a issue with a competency framework:
Name: Fiber Optics Installer (FOI)
Ctid:   ce-b14e18d5-daa7-4b56-ba75-3b4fb12860d0
 
I logged in as the user, saw the framework, and approved it.

I tried to search for the framework, both as the user, and again as an admin, and the framework cannot be found!

@eddavies can you investigate this?

**Comment by eddavies** [comment] 2019-01-25 19:06
Looking into it now.

**Comment by Lomilar** [comment] 2019-02-27 20:42
Need to comb the version history to find it.

**Comment by jkitchensSIUC** [comment] 2019-06-15 14:04
@cwd-mparsons @Lomilar is this still an issue?

**Comment by Lomilar** [comment] 2019-06-19 18:10
Yes, to be investigated. It seems to be a one-off at the moment, unless anyone has knowledge otherwise.

**Comment by Lomilar** [comment] 2019-07-17 17:40
Process for investigating:
* Go to database, investigate ElasticSearch /permanent index, /*.Competency index, look for that CTID.
* If found, go find logs that indicate it was modified.
* Continue Root Cause Analysis.

**Comment by woodkri** [comment] 2019-07-19 19:07
Most recent version of the framework here: https://cass.credentialengine.org/api/data/9fcf3ee7fe54fbd6f8f5c7b015ad7fd7.13

I checked the tomcat logs for that day and there are some posts for that framework, followed by a delete:

[24/Jan/2019:15:32:45 -0600] "DELETE /api/data/schema.cassproject.org.0.3.Framework/9fcf3ee7fe54fbd6f8f5c7b015ad7fd7 HTTP/1.1" 200 5

**Comment by Lomilar** [comment] 2019-07-29 15:21
Thank you. @siuc-nate @cwd-mparsons copy? Looks like it got deleted.

**Comment by cwd-mparsons** [comment] 2019-07-29 15:52
The initial description of the issue was:
- found the framework
- approved the framework (which may have required first editing and saving the framework)
- using the search both as the partner user, and as myself, could not find the framework (not clear in the initial description whether the search was done immediately or later)

In the latter scenario, I cannot see how I could have 'accidentally' deleted the framework between the approval and the search. 
I see that the framework had already been republished with a different CTID. 
I am closing the issue. We have an open item log delete events from CaSS. Once the latter is implemented, we will be able to be trace the issue should it occur again.

**Closed by cwd-mparsons** 2019-07-29 15:52 UTC
Labels: Credential Engine CaSS, High Priority, bug, needs repro
