### ISSUE TITLE
Autosuggest / validate language tags.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#134] opened 2018-03-02 17:54 UTC
Language tags are complex.

https://www.w3.org/International/articles/language-tags/

Autosuggesting valid tags is recommended, and if there exist libraries for language code validation, we should use those.

**Comment by eddavies** [comment] 2018-04-03 21:14
Both the concept editor and the framework editor are populating language tags. I honestly don't know anything about these tags, but a ton are popping up.

**Comment by Lomilar** [comment] 2018-04-03 23:01
Yeah. If the framework has a language tag, it propagates to each competency in the framework. That's on purpose.

**Comment by Lomilar** [comment] 2018-04-04 20:28
This is fine. "inLanguage" describes the language that the competency is thought about it, was taught in, or is reasoned in. As an example, we're good at counting using Arabic numbers (1,2,3) in English, but that differs from counting using Chinese numbers in Mandarin, or counting using Chinese numbers in Cantonese.

That differs from the languages used to describe the data, 使用英文阿拉伯数字（1,2,3）进行计数, which described counting using Arabic numbers in English (described in Simplified Chinese)

**Comment by eddavies** [comment] 2018-04-04 20:46
Ok, this function is working as intended then. Closing this issue

**Closed by eddavies** 2018-04-04 20:46 UTC
