### ISSUE TITLE
Display additional data for "Creator" and "Publisher" on the framework view screen

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#323] opened 2018-06-25 21:20 UTC
This should include user-friendly data such as name, description, subjectWebpage, etc.  This should ideally come from the registry on-demand.

**Comment by stuartasutton** [comment] 2018-06-25 21:35
Whoa, what are we talking about here? Are we talking about the left-hand display in the CASS viewer or the TOC of frameworks?  The TOC needs no more than the description and publisher name. I think that that is also sufficient for the left-hand panel in the CASS viewer.

**Comment by siuc-nate** [comment] 2018-06-25 21:49
I'm referring to this:
![image](https://user-images.githubusercontent.com/21346519/41877650-b3c2c808-7897-11e8-904f-f5b562a867c7.png)

A user isn't going to know what to do with the JSON at the other end of those URLs.

**Comment by Lomilar** [comment] 2018-06-26 22:46
Accepted (I thought we had an issue already for this.)

Creator and Publisher should be a blue link with the creator/publisher name (if retrievable) that link to the data.

**Comment by stuartasutton** [comment] 2018-06-26 22:59
I need to push back a bit. If you resolve all of these URIs so there is nothing left but pretty text, how does someone who needs the URI for linking get to the URIs? (I'll reserve the groan until you tell me I need to download the json-ld to get them.) This is an editor and the values of the properties are URIs.

Maybe we should have a little toggle by each object field (URI) that allows us to toggle the literal off and the URI on.

**Comment by Lomilar** [comment] 2018-06-26 23:03
They right click and "copy link"?

[like this?](http://google.com)

**Comment by siuc-nate** [comment] 2018-06-27 14:04
>If you resolve all of these URIs so there is nothing left but pretty text, how does someone who needs the URI for linking get to the URIs?

Hence "additional" - the URIs should still be visible, but there should be something for the average Joe to look at, too.

**Comment by Lomilar** [comment] 2018-06-27 18:01
We could also explore icons and whatnot.

I'm used to hovering links to see what the URL is. Is that not desired? Something like...

Creator Name [🔗](http://google.com) <-- with the URL in there.

We all may be the wrong people to make this decision, except Nate.

**Comment by siuc-nate** [comment] 2018-06-28 14:12
Maybe something simple, e.g.

**Publishing Organization Name**
https://credentialengineregistry.org/resources/ce-[GUID]

Where the URL is a smaller font to downplay it and help keep it from wrapping on most screens (not a huge deal)

**Comment by stuartasutton** [comment] 2018-06-28 14:28
Also (or maybe even best) is Fritz' suggestion of text with appended [🔗](http://google.com). Of course, some layperson will click it as well and be "confused"...but we have to find some middle ground. My take is that such a person will only click it once :-)

**Comment by siuc-nate** [comment] 2018-06-28 14:29
Perhaps a small version of the JSON logo/icon?

**Comment by stuartasutton** [comment] 2018-06-28 14:33
Nope, that would be confusing...prefer Fritz' link icon.

**Comment by Lomilar** [comment] 2018-06-29 18:18
I have been chastised by designers about using emoji as icons, so I'd recommend for final implementation equivalents from FontAwesome or the like.

![image](https://user-images.githubusercontent.com/337692/42107972-0e18b1fc-7b8e-11e8-86fc-83740c23c7ab.png)

**Comment by stuartasutton** [comment] 2018-06-30 12:03
As I think more about this, the functionality for the user is to copy a URI for pasting it into his or her own linked metadata, not to resolve the underlying link of a literal (can't assume that the user knows how to read json-ld).  This is complex because we have taken the actual property value of, say, the creator, resolved that URI to get the associated literal and displayed it, and now  want to provide the means for an end user wanting to link to that resource to grab the underlying URI that we resolved.  No icon I am aware of works: (1) a link icon doesn't work because I don't want to resolve the URI, I want to copy it; and (2) a copy icon doesn't work because it logically means "copy the literal" to the user, which is not the affect.

So, I guess it means that we have to settle for the literal being an active link knowing that if clicked, it will confuse the naive user but resolve to something where the URI can be found by the user who understands json-ld that wants to link some other entity to the underlying entity. The savvy user will catch on quickly that they can do a fast link copy with keyboard sort cuts.

**Comment by stuartasutton** [comment] 2018-06-30 12:08
The only solution that would be clear and serve both types of user would be to provide functionality that allows the user to toggle between two views: (1) a view of nothing but literals (all URIs resolved), and (2) a second view that displays URIs of all object properties as URIs (not literals).

**Comment by Lomilar** [comment] 2018-07-05 20:18
I'm still not sure why a simple link wouldn't suffice.

Is copying the address from a link not standard practice? I probably do it a couple times a day.

![image](https://user-images.githubusercontent.com/337692/42345950-da8fd3de-8055-11e8-90c0-9ed6fd9d78a1.png)

**Comment by Lomilar** [comment] 2018-07-05 20:37
We could do a click based copy to clipboard (instead of navigate) with a little message... though that wouldn't be the expected behavior from clicking on a link. We'd need some sort of clipboard icon instead.

[Creator.Name](http://google.com) 📋 <-- copies the URL to the clipboard.

**Comment by stuartasutton** [comment] 2018-07-05 21:24
Thanks, Fritz...this is right thinking...

**Comment by eddavies** [comment] 2018-07-12 18:15
The copy icon works. Closing this. Feel free to reopen if there are additional concerns revolving this.

**Closed by eddavies** 2018-07-12 18:15 UTC
Labels: High Priority, enhancement
