### ISSUE TITLE
A duplicated element (narrows two competencies) only has subcompetencies for one.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#291] opened 2018-05-24 18:19 UTC
![image](https://user-images.githubusercontent.com/337692/40503864-4c33f296-5f44-11e8-84dc-0bc9401d71c3.png)

**Comment by miledivovic** [comment] 2018-07-02 16:34
This might have been fixed? I'm not able to reproduce.

**Comment by chinhseah** [comment] 2018-07-02 17:02
@eddavies Could you test if this is working?

**Comment by eddavies** [comment] 2018-07-02 17:10
yeah, testing it now

**Comment by eddavies** [comment] 2018-07-02 17:13
Since narrow alignments no longer create children, is this even reproducible?

**Comment by eddavies** [comment] 2018-07-02 17:14
ignore the comment I just deleted

**Comment by eddavies** [comment] 2018-07-02 17:23
this bug no longer occurs, but I have a couple questions @Lomilar . 
Creating narrow alignments with competencies in the same framework does not create a narrow alignment that appears in connections, but creates children. Is this intended (seems like it should, but we do not message that to the user)?
In this below image, I checkmarked two parenting competencies to be aligned and so it duplicated them twice under the aligning parent. This seems correct, but just want to make sure this is intended?
<img width="412" alt="extra unders" src="https://user-images.githubusercontent.com/23706850/42177469-af55aa0c-7de1-11e8-8fdc-2a808a20d1ed.PNG">

**Comment by eddavies** [comment] 2018-07-05 18:41
Closing this. Have not been able to reproduce this bug.

**Closed by eddavies** 2018-07-05 18:41 UTC
Labels: bug
