### ISSUE TITLE
Competency hierarchy needs global expand/collapse icons

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#366] opened 2018-08-10 14:08 UTC
Currently, we have the "+" and "-" to expand and contract **sections** of a competency framework. In addition, we need an icon or icons somewhere at the top of the hierarchy pane for globally expanding and collapsing an entire framework. 

Some frameworks are potentially massive, and being able to expand/collapse makes it possible to jump out to a view of the top-level nodes so you can move quickly as you edit.

E.g., the following icons appear at the top of the ASN-US (D2L) hierarchies for global collapsing and expanding:

<img width="62" alt="screenshot 2018-08-10 07 00 03" src="https://user-images.githubusercontent.com/2939046/43962114-b06a7280-9c6b-11e8-9913-143d096e5795.png">

**Comment by Lomilar** [comment] 2018-08-20 15:11
Also implementing standard behavior for * and / on the keypad (expand all and collapse all) would be beneficial here.

**Comment by chinhseah** [comment] 2018-10-16 19:06
Please give any feedback on button to collapse all competencies within a framework (see attached screen capture):

![collapse all button](https://user-images.githubusercontent.com/15805943/47040683-b3865100-d13b-11e8-9291-6c5c3719e2de.PNG)

Please give any feedback on button to expand all competencies within a framework (see attached screen capture):

![expand all button](https://user-images.githubusercontent.com/15805943/47040692-b7b26e80-d13b-11e8-97c3-5ea1af1c9268.PNG)

**Comment by stuartasutton** [comment] 2018-10-17 12:13
Yes, this looks good.

**Comment by eddavies** [comment] 2018-10-23 17:38
@chinhseah Has this been implemented on test? I don't see it.

**Comment by Lomilar** [comment] 2018-10-23 17:57
Reproduced @eddavies note on CTITest.

**Comment by chinhseah** [comment] 2018-10-23 18:18
@Lomilar I just checked and I have code to enable buttons, for collapse and expand all, in viewFramwork.js but not in cass-editor.js. I had some issues with merging into master yesterday because pull request 398 was so old that there were many conflicts that had to be resolved.

**Comment by Lomilar** [comment] 2018-10-23 19:58
Ah, run `mvn install` and commit and push.

**Comment by Lomilar** [comment] 2018-10-24 14:59
Global expand and collapse take up column space on CTITest.
![image](https://user-images.githubusercontent.com/337692/47440274-ab916700-d762-11e8-9eb3-d7f47baf9b2c.png)

May be able to reproduce using a wordy framework or using ?link=true

**Comment by chinhseah** [comment] 2018-10-24 15:58
@Lomilar I guess putting 2 buttons there wasn't such a good idea. How about if I put the 2 buttons at the top/start of listing of competencies? What do you think?

**Comment by Lomilar** [comment] 2018-10-24 17:18
The buttons are fine, they just need to right-align in the same area as the labels. float:right may not be sufficient, making the buttons smaller may also work.

**Comment by chinhseah** [comment] 2018-10-24 22:42
@Lomilar @eddavies I fixed "column space" problem.
![collapse expand overflow fix2](https://user-images.githubusercontent.com/15805943/47465793-49a52180-d7a3-11e8-911c-ea085bb1471a.JPG)
I tested with a "wordy framework" as well:
![collapse expand overflow fix1](https://user-images.githubusercontent.com/15805943/47465800-4f026c00-d7a3-11e8-8a43-dc1ed526e0d9.JPG)

**Comment by Lomilar** [comment] 2018-10-25 15:28
There's a little visual artifact where the bottom of the scroller is clipped off.
![image](https://user-images.githubusercontent.com/337692/47511843-e1e8e800-d82f-11e8-8015-f92bb0aade51.png)

**Comment by chinhseah** [comment] 2018-10-25 18:44
@Lomilar @eddavies I fixed the scrollbar so 'down arrow' at the bottom is displayed.
![competency list vertical scrollbar 2](https://user-images.githubusercontent.com/15805943/47522742-3f3e6280-d84b-11e8-8e91-4b92cd1d3117.JPG)

![competency list vertical scrollbar 1](https://user-images.githubusercontent.com/15805943/47522765-4e251500-d84b-11e8-9341-6d5143f72751.JPG)

**Comment by Lomilar** [comment] 2018-10-25 19:52
Cool, thanks. @eddavies all yours.

**Comment by eddavies** [comment] 2018-10-26 23:06
Looks good except for one minor thing. The yellow border for when one is selected is cutoff at the bottom:
<img width="761" alt="yellow highlight" src="https://user-images.githubusercontent.com/23706850/47596124-041a5d00-d939-11e8-9460-306cc0a70206.PNG">

**Comment by Lomilar** [comment] 2018-10-31 17:40
Should be fixed in https://github.com/cassproject/cass-editor/pull/416

**Comment by eddavies** [comment] 2018-10-31 18:06
Looks good now.

**Closed by eddavies** 2018-10-31 18:06 UTC
Labels: enhancement
