### ISSUE TITLE
Pressing enter in the competency framework editor screen loads the concept selector regardless of which field is focused

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#248] opened 2018-04-30 21:31 UTC
While creating/editing a competency framework, pressing enter with the cursor in the description field brings up an interface to select a concept.  This part of the interface is much further down in the form and should not respond to enter key presses while another field is focused.

**Comment by Lomilar** [comment] 2018-05-01 16:01
Duplicate of #205

**Closed by Lomilar** 2018-05-01 16:01 UTC
Labels: duplicate
