### ISSUE TITLE
Enable the user to download a template CSV file for each of the allowed types on the "Import Framework" screen

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#321] opened 2018-06-25 21:15 UTC
This will help the user provide correct data, and should work similarly to the Bulk Upload tool for credentials.  This would essentially be an export of a blank/empty framework (or, more usefully, one with predetermined sample data for each field).

**Comment by siuc-nate** [comment] 2018-06-25 21:16
@stuartasutton @jkitchensSIUC @cwd-mparsons We will need to determine which properties are appropriate to include in such a template when it comes to CTDL-ASN, so as not to confuse users.

**Comment by Lomilar** [comment] 2018-06-26 22:34
Related to #160.

Medbiq and ASN are not spreadsheet based formats.

**Comment by Lomilar** [comment] 2018-07-09 21:18
See https://credentialengine.org/publisher/BulkUpload for inspiration.

**Comment by eddavies** [comment] 2018-10-03 18:07
I'm getting stuck on this for the CaSS sample csv with it's relation import:
<img width="917" alt="importing cass samples" src="https://user-images.githubusercontent.com/23706850/46429912-731ae200-c6fc-11e8-84c6-39097ea7bc61.PNG">

**Comment by eddavies** [comment] 2018-10-03 18:08
Everything else is working

**Comment by eddavies** [comment] 2018-10-03 18:40
The CaSS sample csv actually imported as I can see it on the framework list. Just the swirl never disappeared during the import process.

**Comment by woodkri** [comment] 2018-12-06 15:19
I haven't been able to reproduce this.

**Comment by eddavies** [comment] 2018-12-06 20:33
I cannot reproduce this anymore, may have been fixed by previous import changes

**Closed by eddavies** 2018-12-06 20:33 UTC
Labels: enhancement, needs repro
