### ISSUE TITLE
Check mappings for CTDL-ASN concept schemes

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#489] opened 2019-02-01 20:30 UTC
Namespaces have changed for some properties, per the mapping spreadsheet.

**Comment by woodkri** [comment] 2019-02-08 15:58
@Lomilar I believe the fields are all the same for concept schemes whether in ceasn mode or not. Moving forward do we want to differentiate these and have separate namespaces for the two, or should CaSS fields also be moved over to the ceasn namespace?

**Comment by stuartasutton** [comment] 2019-02-08 16:17
For what it is worth, the SKOS specification for skos:ConceptScheme defines one single property--skos:hasTopChild. To make any other assertions via the skos:ConceptScheme, we have to use properties from other namespaces. For skos:ConceptScheme, all additional properties come from CEASN.

For skos:Concept, **all properties** we use (at least at the moment)  come directly from the SKOS namespace

**Comment by Lomilar** [comment] 2019-03-01 20:12
We're going after this by having a CTDL-ASN profile of SKOS. Currently, CaSS is using DC properties for metadata.

Concept scheme import from CTDL-SKOS is #378, Concept scheme export to CTDL-SKOS is #77.

**Comment by Lomilar** [comment] 2019-03-20 19:36
https://github.com/CredentialEngine/vocabularies/issues/588
Update descriptions and names of fields in the editor to match the fields in this issue.

**Comment by siuc-nate** [comment] 2019-04-03 20:01
Per our 4-3-2019 meeting:
@stuartasutton will setup the terms for this.

**Comment by Lomilar** [comment] 2019-05-08 19:17
Ongoing, waiting for descriptions of the skos terms for the CaSS Editor? (related vs relatedMatch)

**Comment by stuartasutton** [comment] 2019-05-08 23:22
I'm not sure exactly what the problem is.

**Comment by woodkri** [comment] 2019-05-09 12:53
We had discussed CaSS Editor having both skos:related and skos:relatedMatch for concepts. I just need a description of both before I can add them to the editor.

**Comment by Lomilar** [comment] 2019-05-29 19:48
Could you provide descriptions (tooltips) for skos:related and skos:relatedMatch that highlight and distinguish their use in the editor?

relatedMatch: CredentialEngine/vocabularies#588
related: CredentialEngine/vocabularies#607

**Comment by Lomilar** [comment] 2019-06-12 20:04
Related is intra-framework references, and relatedMatch is inter-framework references.

**Comment by Lomilar** [comment] 2019-06-12 20:07
[ ] Edit in the editor
[ ] Edit in the schema spreadsheet

**Comment by woodkri** [comment] 2019-06-13 20:13
Also to do: Add to schema translation

**Comment by woodkri** [comment] 2019-06-14 18:15
skos:related has been added to the Credential Engine profile of the editor, and there is a pull request open to add it to the export translation.

**Comment by Lomilar** [comment] 2019-06-19 18:07
PR merged.

**Comment by Lomilar** [comment] 2019-07-17 17:41
skos:related needs to be added to the CE Terms Mapping Spreadsheet, then can close this.

**Comment by stuartasutton** [comment] 2019-07-31 15:25
This has been updated in https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1140243756.  The `relatedMatch` property has been deleted and `related` property added and its definition updated to simply: "URL of an associatively related concept". Note that it does not have the "...in the same scheme" language meaning that it's applicable in relating concepts in the same concept scheme and in other concept schemes.

**Closed** 2019-07-31 20:21 UTC
Labels: Concept Scheme, Credential Engine CaSS, High Priority, pending
