### ISSUE TITLE
Editor not allowing editing of top-level competency

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#353] opened 2018-07-20 20:53 UTC
Here's a video of me trying.

http://www.screencast.com/t/Duo2zDZY

**Comment by miledivovic** [comment] 2018-07-20 21:05
This looks to me like its being caused by the same bug as #338.

**Comment by eddavies** [comment] 2018-09-06 19:40
I'm not running into this on test. @stuartasutton are you still running into this on production?

**Comment by stuartasutton** [comment] 2018-09-06 19:42
No, this should have been closed long ago.

**Comment by eddavies** [comment] 2018-09-06 19:50
Thanks, closing

**Closed by eddavies** 2018-09-06 19:50 UTC
Labels: High Priority, bug
