### ISSUE TITLE
Production competency editor having problems editing files

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#338] opened 2018-07-06 20:31 UTC
I just started editing some frameworks on the production server at https://credentialengine.org/publisher/competencies/ --specifically, the "Certified Information Systems Security Professional (CISSP) Exam Competencies" framework.  I'm fine editing the framework, but when I try to edit a competency, it gives me part of the framework metadata instead to edit...it also gives me a bunch of properties that it should not be there:  Notation, Alternate Name, Hidden Label, Note, Change Note...these feel like SKOS.

HOWEVER, when I go to edit a record I've edited before, all of this strange behavior disappears.

**Comment by eddavies** [comment] 2018-07-07 00:59
Looking into this. I just found an occurrence where some fields were not saving correctly as well.

**Comment by stuartasutton** [comment] 2018-07-08 14:41
Please let me know as soon as it is fixed. Editing of records has come to a halt.

**Comment by miledivovic** [comment] 2018-07-10 16:24
@stuartasutton I'm trying to narrow down what could be the cause of this, does this issue also occur on newly created frameworks?

**Comment by stuartasutton** [comment] 2018-07-10 16:31
Sorry, I don't know since I don't create anything new on the production server...only edit existing frameworks.

**Comment by stuartasutton** [comment] 2018-07-10 16:39
All I can say is that I edited many files and can open any of those previously edited files and have continue editing. Since the problem arose app. 4 days ago, I can't edit anything that had not been previously edited because trying to edit a competency defaults back to the framework to edit.

**Comment by Lomilar** [comment] 2018-07-13 18:34
Apologies for not updating this earlier. We had a discussion about this bug and were unable to reproduce it on test, which led us to believe that it had been fixed as part of previous issues.

Going to leave it open until we get this on production where we can confirm it is fixed.

**Comment by stuartasutton** [comment] 2018-07-13 19:08
No, it is not fixed. On the production server, try "Certificate in Pharmacy Technician". When you try to edit any competency, the text in the editor shifts to the framework even though the competency is highlighted.

But, **and I am not sure this is being heard**, if I go to edit a record that I edited before the date the problem arose (e.g., "CCO Digger Derrick Operator Written Exam"), all is well, works just fine.

What have I done to test this out? I've tried it on two machines using two different browsers (clearing cache).

**Comment by eddavies** [comment] 2018-08-08 17:45
@stuartasutton is this now fixed on production?

**Comment by stuartasutton** [comment] 2018-08-09 13:52
I have not experienced this problem since the update to the production server.

**Comment by eddavies** [comment] 2018-08-09 20:59
Closing this, feel free to reopen if the error pops up again.

**Closed by eddavies** 2018-08-09 20:59 UTC
Labels: High Priority, blocker, bug
